/* Populate table customers */
-- INSERT INTO regions (id, name) VALUES (1, 'South America');
-- INSERT INTO regions (id, name) VALUES (2, 'Europe');
-- INSERT INTO regions (id, name) VALUES (3, 'Asia');
-- INSERT INTO regions (id, name) VALUES (4, 'Africa');
-- INSERT INTO regions (id, name) VALUES (5, 'Oceania');
-- INSERT INTO regions (id, name) VALUES (6, 'Antarctica');
-- INSERT INTO regions (id, name) VALUES (7, 'North America');
-- INSERT INTO regions (id, name) VALUES (8, 'South America');
-- INSERT INTO regions (id, name) VALUES (9, 'Central America');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO customers (name, last_name, email, created_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06');
INSERT INTO customers (name, last_name, email, created_at) VALUES('John', 'Smith', 'john.smith@example.com', '2018-03-07');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Jane', 'Doe', 'jane.doe@example.com', '2018-03-08');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Bob', 'Marley', 'bob.marley@example.com', '2018-03-09');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Michelle', 'Obama', 'michelle.obama@example.com', '2018-03-10');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Michael', 'Jordan', 'michael.jordan@example.com', '2018-03-11');
INSERT INTO customers (name, last_name, email, created_at) VALUES('William', 'Shakespeare', 'william.shakespeare@example.com', '2018-03-12');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Taylor', 'Swift', 'taylor.swift@example.com', '2018-03-13');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Justin', 'Bieber', 'justin.bieber@example.com', '2018-03-14');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Serena', 'Williams', 'serena.williams@example.com', '2018-03-15');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Maria', 'Sharapova', 'maria.sharapova@example.com', '2018-03-16');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Roger', 'Federer', 'roger.federer@example.com', '2018-03-17');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Rafael', 'Nadal', 'rafael.nadal@example.com', '2018-03-18');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Novak', 'Djokovic', 'novak.djokovic@example.com', '2018-03-19');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Cristiano', 'Ronaldo', 'cristiano.ronaldo@example.com', '2018-03-20');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Lionel', 'Messi', 'lionel.messi@example.com', '2018-03-21');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Lebron', 'James', 'lebron.james@example.com', '2018-03-22');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Stephen', 'Curry','stephen.curry@example.com', '2018-03-23');
INSERT INTO customers (name, last_name, email, created_at) VALUES('James', 'Harden', 'james.harden@example.com', '2018-03-24');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Kevin', 'Durant', 'kevin.durant@example.com', '2018-03-25');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Kobe', 'Bryant', 'kobe.bryant@example.com', '2018-03-26');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Michael', 'Phelps', 'michael.phelps@example.com', '2018-03-27');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Usain', 'Bolt', 'usain.bolt@example.com', '2018-03-28');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Tom', 'Brady', 'tom.brady@example.com', '2018-03-29');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Aaron', 'Rodgers', 'aaron.rodgers@example.com', '2018-03-30');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Simone', 'Biles','simone.biles@example.com', '2018-03-31');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Katie', 'Ledecky', 'katie.ledecky@example.com', '2018-04-01');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Michael', 'Johnson', 'michael.johnson@example.com', '2018-04-02');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Florence', 'Griffith','florence.griffith@example.com', '2018-04-03');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Carl', 'Lewis', 'carl.lewis@example.com', '2018-04-04');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Andre', 'Agassi','andre.agassi@example.com', '2018-04-05');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Pete','Sampras','pete.sampras@example.com', '2018-04-06');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Venus','Williams','venus.williams@example.com', '2018-04-07');
INSERT INTO customers (name, last_name, email, created_at) VALUES('David','Beckham','david.beckham@example.com', '2018-04-08');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Wayne','Gretzky','wayne.gretzky@example.com', '2018-04-09');
INSERT INTO customers (name, last_name, email, created_at) VALUES('Joe','Montana','joe.montana@example.com', '2018-04-10');
/* Create some products */
-- INSERT INTO products (name, price, created_at) VALUES('Blue shirt', 100, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Black pants', 200, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Red socks', 300, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Green sweater', 400, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('White cap', 500, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Brown backpack', 600, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Silver watch', 700, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Brown shoes', 800, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Black belt', 900, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Sunglasses', 1000, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Gray scarf', 1100, NOW());
-- INSERT INTO products (name, price, created_at) VALUES('Yellow gloves', 1200, NOW());
/* Create some invoices */
-- INSERT INTO bills (description, observation, client_id, created_at) VALUES('Shirt purchase invoice',null, 1, NOW());
-- INSERT INTO bills_items (quantity, bill_id, product_id) VALUES(1,1,1);
-- INSERT INTO bills_items (quantity, bill_id, product_id) VALUES(2,1,4);
-- INSERT INTO bills_items (quantity, bill_id, product_id) VALUES(1,1,5);
-- INSERT INTO bills_items (quantity, bill_id, product_id) VALUES(1,1,7);
-- INSERT INTO bills (description,observation, client_id, created_at) VALUES('Pants purchase invoice','Out of season', 1, NOW());
-- INSERT INTO bills_items (quantity, bill_id, product_id) VALUES(3,2,2);
